### ISSUE TITLE
anyplan support pose model with onnx?

### ISSUE THREAD

**Issue by trouble-maker007** [ibaiGorordo/Sapiens-Pytorch-Inference#1]

**Comment by ibaiGorordo** [comment]
Not really. Before Sapiens was published I was working on the RTMPose ONNX models (https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose), which I think are better in terms of speed. I will probably release an example for those next week.

**Comment by Jaykumaran** [comment]
Hello,

If you are looking for Pose Estimation task using this pipeline, you can check my fork which is yet to be reviewed and PR merged.


https://github.com/Jaykumaran/Sapiens-Pytorch-Inference

However i've not experimented with onnx porting.


References:

https://learnopencv.com/sapiens-human-vision-models/

https://github.com/spmallick/learnopencv/blob/master/Sapiens-Human-Vision-Model-Meta/Sapiens_Pose%2BDepth%2BNormal%2BPart_Seg.ipynb

**Comment by ibaiGorordo** [comment]
Merged the PR.

@Jaykumaran Thanks!
