### ISSUE TITLE
Inference issue

### ISSUE THREAD

**Issue by timothyafolami** [ibaiGorordo/Sapiens-Pytorch-Inference#2]
![image](https://github.com/user-attachments/assets/7f954aa1-97b3-4254-aa82-fd03c48c3acc)

Firstly thanks for creating this.. 

I was experiencing this error while testing the code you shared for inference.

**Comment by ibaiGorordo** [comment]
I think float16 is not supported on your device, I just commented all the float16 in the examples. Try pulling the latest changes, or otherwise comment this line:
https://github.com/ibaiGorordo/Sapiens-Pytorch-Inference/blob/34439e7d1219d263fbf9e82ffc25d7e714df14b3/image_predictor.py#L8

**Comment by timothyafolami** [comment]
okay, thanks.
