### ISSUE TITLE
404 Error While Downloading sapiens_1b_normal_render_people_epoch_115_torchscript.pt2 from Hugging Face Hub

### ISSUE THREAD

**Issue by dhruvin771** [ibaiGorordo/Sapiens-Pytorch-Inference#5]
![image_2024_10_16T11_38_27_438Z-1.png](https://github.com/user-attachments/assets/29984a6c-b573-469a-bdff-414c07d6e602)

**Comment by Jaykumaran** [comment]
Hi,

The Sapiens repository has been refactored, you can download the model and place in respective model dir from 

https://huggingface.co/facebook/sapiens.


Place the files, automatically others will work.


If you are interested, you can go through LearOpenCV article which uses this Sapiens pipeline


https://learnopencv.com/sapiens-human-vision-models/

Updated Code:https://github.com/spmallick/learnopencv/blob/master/Sapiens-Human-Vision-Model-Meta/Sapiens_Pose%2BDepth%2BNormal%2BPart_Seg.ipynb


I ve added Pose Estimation Code in my fork, which is yet to be PR merged

https://github.com/Jaykumaran/Sapiens-Pytorch-Inference


Hope this helps. 

Let me know if you face any issues

**Comment by Jaykumaran** [comment]
Feel free to close this issue if you got a fix

**Comment by dhruvin771** [comment]
> Hi,
> 
> The Sapiens repository has been refactored, you can download the model and place in respective model dir from 
> 
> https://huggingface.co/facebook/sapiens.
> 
> 
> Place the files, automatically others will work.
> 
> 
> If you are interested, you can go through LearOpenCV article which uses this Sapiens pipeline
> 
> 
> https://learnopencv.com/sapiens-human-vision-models/
> 
> Updated Code:https://github.com/spmallick/learnopencv/blob/master/Sapiens-Human-Vision-Model-Meta/Sapiens_Pose%2BDepth%2BNormal%2BPart_Seg.ipynb
> 
> 
> I ve added Pose Estimation Code in my fork, which is yet to be PR merged
> 
> https://github.com/Jaykumaran/Sapiens-Pytorch-Inference
> 
> 
> Hope this helps. 
> 
> Let me know if you face any issues
> 
> 
> 
> 

Thank you, it's worked
